# -*- coding: utf-8 -*-
"""scraping berita Kominfo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14E-1RjOf7RensZLgyaulDZBjAvyRtMd5
"""

!pip install newspaper3k
!pip install Sastrawi
!pip install stopword

import newspaper
from newspaper import news_pool
from newspaper import Article

list_of_urls = ['https://www.kominfo.go.id/content/detail/49423/disinformasi-kpu-nyatakan-ganjar-pranowo-gagal-daftar-pilpres-2024/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/48023/hoaks-dirut-pertamina-sita-aset-ahok-untuk-ganti-rugi-kebakaran-depo-pertamina-plumpang/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/47849/disinformasi-pertamax-berisi-pertalite/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/27783/disinformasi-mobil-wakil-presiden-kehabisan-bensin-diisi-dengan-bensin-eceran-di-pinggir-jalan/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/47746/disinformasi-bbm-langka-akibat-depo-pertamina-plumpang-terbakar/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/30082/disinformasi-kebakaran-sebuah-kafe-di-malioboro-karena-gas-air-mata/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/47148/hoaks-tautan-kuesioner-berhadiah-subsidi-bbm-pertamina-senilai-rp5-juta/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/30082/disinformasi-kebakaran-sebuah-kafe-di-malioboro-karena-gas-air-mata/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/46179/pemerintah-proyeksikan-perekonomian-nasional-2023-tumbuh-53-persen/0/berita',
                'https://www.kominfo.go.id/content/detail/46101/hoaks-pertamina-bagikan-subsidi-bbm-rp700-ribu-untuk-peringati-hut-ke-55/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/46066/hoaks-pengisian-bbm-gratis-pada-31-november-2022/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44909/disinformasi-pertalite-yang-dijual-pertamina-berkadar-ron-86/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44907/hoaks-perbandingan-pertalite-lama-dan-pertalite-baru-yang-berubah-warna-serta-lebih-boros/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44671/awas-disinformasi-massa-bakar-pos-polisi-saat-demonstrasi-tolak-kenaikan-bbm/0/berita_satker',
                'https://www.kominfo.go.id/content/detail/44730/disinformasi-tautan-pencairan-bansos-subsidi-bbm-tahun-2022/0/laporan_isu_hoakss',
                'https://www.kominfo.go.id/content/detail/44656/disinformasi-video-pos-polisi-dibakar-pada-aksi-demonstrasi-tolak-kenaikan-harga-bbm/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44655/disinformasi-video-detik-detik-presiden-jokowi-lari-ketakutan-saat-demo-tolak-kenaikan-bbm/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44561/disinformasi-presiden-joko-widodo-marah-karena-kenaikan-harga-bbm-dan-bahan-pokok/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44456/disinformasi-video-unjuk-rasa-mahasiswa-terkait-kenaikan-harga-bbm-dan-tuntut-presiden-jokowi-mundur/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44393/disinformasi-stok-bbm-langka-akibat-kebakaran-tangki-terminal-minyak-balongan/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44381/disinformasi-dana-blt-bbm-merupakan-dana-desa-yang-direalokasi/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44380/disinformasi-pemerintah-sengaja-merekayasa-status-ppkm-untuk-meredam-massa-demonstrasi-kenaikan-harga-bbm/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44220/disinformasi-670-sepeda-listrik-disumbangkan-gratis-setelah-harga-bbm-naik/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44179/disinformasi-pom-bensin-tuban-dibakar-massa-setelah-harga-bbm-naik-pada-3-september-2022/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/44075/hoaks-selebaran-kenaikan-harga-bbm-1-september-2022/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/43611/disinformasi-kebakaran-tangki-bbm-di-depan-alfamart-purwokerto/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/42711/hoaks-isi-bensin-di-spbu-dengan-nominal-ganjil-bisa-menghindari-kecurangan/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/41215/disinformasi-2-balita-tewas-dalam-kecelakaan-truk-spbu-di-karanganyar/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/38966/hoaks-imbauan-mengisi-penuh-bbm-kendaraan-karena-adanya-mogok-kerja-pegawai-pt-pertamina/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/37994/hoaks-kelangkaan-bbm-di-kota-sorong/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/32640/disinformasi-isi-bbm-gratis-pada-29-dan-30-februari-2021/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/28829/disinformasi-jalan-layang-tol-cikampek-bergelombang-gara-gara-digunakan-untuk-uji-coba-esemka-ribuan-unit/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/27258/hoaks-pt-pertamina-persero-akan-menghapus-bbm-jenis-premium-dan-pertalite/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/26211/hoaks-draf-harga-bbm-baru-berlogo-pertamina/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/25680/hoaks-peduli-covid-19-pertamina-turunkan-harga-bbm-hingga-50-persen/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/24572/hoaks-gratis-bbm-pada-tanggal-30-dan-31-februari-2020/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/23966/disinformasi-kebakaran-di-spbu-selaganggeng/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/22767/hoaks-segera-isi-bbm-karna-malam-ini-harganya-akan-naik/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/21463/disinformasi-selebrasi-jokowi-atas-kesuksesan-menaikan-pajak-bpjs-bbm/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/20523/hoaks-detik-akibat-pemadaman-listrik-pln-350-ribu-tka-ilegal-dari-rrc-masuk-indonesia/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/17564/hoaks-harga-bbm-di-papua-perliter-77-ribu/0/laporan_isu_hoaks',
                'https://www.kominfo.go.id/content/detail/17202/hoaks-minyak-goreng-bikin-suara-mesin-halus/0/laporan_isu_hoaks'
                ]

import nltk
nltk.download('punkt')
text = []
summarize = []
for url in list_of_urls:
  url_i = newspaper.Article(url="%s" % (url), language='id')
  url_i.download()
  url_i.parse()
  url_i.nlp()
  print('Judul:', url_i.title)
  print('Penulis:', url_i.authors)
  print('Sumber:', url_i.source_url)
  print('Rangkuman :', url_i.summary)
  summarize.append(url_i.summary)
  text.append(url_i.text)

teks_kominfo = ' '.join(map(str, text))

print(teks_kominfo)

import pandas as pd
d = {'teks': [teks_kominfo]}
data_kominfo = pd.DataFrame(data=d)

df_kominfo = pd.DataFrame()
for url in list_of_urls:
  url_i = newspaper.Article(url="%s" % (url), language='id')
  url_i.download()
  url_i.parse()
  url_i.nlp()

  df = pd.DataFrame(columns = ['Judul', 'Penulis', 'Teks', 'Rangkuman', 'Sumber'])

  df['Penulis'] = url_i.authors
  df['Judul'] = url_i.title
  df['Teks'] = url_i.text
  df['Rangkuman'] = url_i.summary
  df['Sumber'] = url_i.source_url

  df_kominfo = df_kominfo.append(df, ignore_index = True)

df_kominfo.head(100)

df_kominfo.to_csv('data berita kominfo.csv', index=True)