# -*- coding: utf-8 -*-
"""scraping berita Kompas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5OOMIESHESua2GAnw18gy9wit64ewar
"""

w!pip install newspaper3k
!pip install Sastrawi
!pip install stopword

import newspaper
from newspaper import news_pool
from newspaper import Article

list_of_urls=['https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2020/01/07/200000769/pengelolaan-bahan-bakar-minyak-bbm-di-indonesia%3Fpage%3Dall&sa=U&ved=2ahUKEwiTyKyn1KT_AhV9RmwGHZbIDBYQFnoECAQQAg&usg=AOvVaw0ZzYaRMoF1F_K5mRQBqQxc',
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2020/02/22/110000369/kapan-bahan-bakar-minyak-habis%3Fpage%3Dall&sa=U&ved=2ahUKEwirpJC02KT_AhXiXWwGHeN_CUkQFnoECAkQAg&usg=AOvVaw376c2ZtjLaP4DjtrUVd0OW",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2022/03/05/141424369/kelebihan-briket-dibanding-bahan-bakar-minyak&sa=U&ved=2ahUKEwirpJC02KT_AhXiXWwGHeN_CUkQFnoECAMQAg&usg=AOvVaw0mN43ZVndfhUPFWNthyji2",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2022/09/03/144500865/rincian-kenaikan-harga-bbm-pertalite-solar-hingga-pertamax-hari-ini%3Fpage%3Dall&sa=U&ved=2ahUKEwirpJC02KT_AhXiXWwGHeN_CUkQFnoECAcQAg&usg=AOvVaw01mmm9ucYUhm80K4vKm2uI",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2022/05/17/101712769/mengapa-penggunaan-bahan-bakar-fosil-menyebabkan-pemanasan-global&sa=U&ved=2ahUKEwirpJC02KT_AhXiXWwGHeN_CUkQFnoECAYQAg&usg=AOvVaw243QBoqigJX1CWLUPVgmpM",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/03/13372151/harga-bbm-pertalite-solar-hingga-pertamax-resmi-naik-mulai-hari-ini&sa=U&ved=2ahUKEwirpJC02KT_AhXiXWwGHeN_CUkQFnoECAgQAg&usg=AOvVaw0txF7mOseH8J02e-qOIYYK",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://otomotif.kompas.com/read/2022/09/03/154100315/cek-harga-bbm-pertamina-shell-bp-dan-vivo-setelah-pertalite-dan-solar-naik%3Fpage%3Dall&sa=U&ved=2ahUKEwirpJC02KT_AhXiXWwGHeN_CUkQFnoECAAQAg&usg=AOvVaw2oRT74LzSipVnYuoqf88Lt",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/03/14262881/alasan-jokowi-tetap-naikkan-harga-bbm-meski-mengaku-pilihan-yang-sulit&sa=U&ved=2ahUKEwirpJC02KT_AhXiXWwGHeN_CUkQFnoECAEQAg&usg=AOvVaw0Mn5o7UzNIhKG0MmGhvtnu",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2020/08/05/160000269/proses-pengolahan-minyak-bumi%3Fpage%3Dall&sa=U&ved=2ahUKEwirpJC02KT_AhXiXWwGHeN_CUkQFnoECAIQAg&usg=AOvVaw0jV-14hVAM49J36ioGPXIM",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://megapolitan.kompas.com/read/2022/09/26/06545081/keluh-kesah-setelah-harga-bbm-naik-antrean-pertalite-di-spbu-mengular%3Fpage%3Dall&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQICBAC&usg=AOvVaw2vS0u3T6fSt3tFSwFiUKr4",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2020/01/08/160000969/jenis-jenis-bbm%3Fpage%3Dall&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQICRAC&usg=AOvVaw3T-s1vObJtWX4euvpsTxAS",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/09/12/141544626/harga-bbm-naik-pemerintah-bakal-salurkan-blt-umkm-rp-12-juta&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQIABAC&usg=AOvVaw0PdNI1OenxY8X2gRpCOuwj",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/03/13503161/harga-bbm-resmi-naik-hari-ini-jokowi-ini-pilihan-terakhir-pemerintah&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQIBhAC&usg=AOvVaw0D0a2L31ozUdWCGs9xRTv8",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/global/read/2021/09/15/032243370/hezbollah-berterima-kasih-bahan-bakar-minyak-iran-akan-tiba-di-lebanon%3Fpage%3Dall&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQIBBAC&usg=AOvVaw2eSpPJeCTggDqAuHt-nKDh",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tag/bahan-bakar&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQIBRAB&usg=AOvVaw0hl_olZTcE9sHuKyrYeFui",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tag/bahan-bakar-minyak&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQIARAB&usg=AOvVaw0B0sFB1XpNUoJXcVute0vw",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2022/05/04/161806969/dampak-pembakaran-bahan-bakar-fosil%3Fpage%3Dall&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQIBxAC&usg=AOvVaw1YC-_SqiqtzhjdAwsqfNqC",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/edu/read/2022/03/27/194700371/itera-inovasi-mobil-berbahan-bakar-minyak-sawit-murni%3Fpage%3Dall&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQIAxAC&usg=AOvVaw3xAceGUbC1mvdCrCnJjBA-",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/wiken/read/2022/05/28/081500681/jadi-produsen-minyak-mentah-kenapa-indonesia-masih-impor-bbm-dari%3Fpage%3Dall&sa=U&ved=2ahUKEwj1j9jl2aT_AhWuTmwGHdhODsE4ChAWegQIAhAC&usg=AOvVaw2zSM-wjJ01zFwCS69HlCRs",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/global/read/2022/04/05/163000370/minyak-goreng-sukses-diuji-coba-jadi-bahan-bakar-pesawat-raksasa-airbus%3Fpage%3Dall&sa=U&ved=2ahUKEwjypbXa2qT_AhV2l1YBHdzeBVU4FBAWegQIBxAC&usg=AOvVaw3e62idts-1yJZmmn6kYUYC",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/03/13503161/harga-bbm-resmi-naik-hari-ini-jokowi-ini-pilihan-terakhir-pemerintah&sa=U&ved=2ahUKEwjypbXa2qT_AhV2l1YBHdzeBVU4FBAWegQICRAC&usg=AOvVaw1ihlKmcSpMzUXMTmJ7prdD",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/global/read/2021/01/18/130558670/inspirasi-energi-7-kendaraan-alternatif-pengganti-mobil-ber-bbm%3Fpage%3Dall&sa=U&ved=2ahUKEwjypbXa2qT_AhV2l1YBHdzeBVU4FBAWegQIAhAC&usg=AOvVaw1Xyb0i0JPgn6Wf7hwxqc-O",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/10/01/045000726/harga-pertamax-turun-ini-daftar-harga-bbm-non-subsidi-per-1-oktober%3Fpage%3Dall&sa=U&ved=2ahUKEwjypbXa2qT_AhV2l1YBHdzeBVU4FBAWegQIBhAC&usg=AOvVaw1wFubc_LUYbzQ5-1wRSNSd",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/12/19/113900726/harga-minyak-dunia-turun-pertamina-review-penurunan-harga-bbm-pertamax-dkk%3Fpage%3Dall&sa=U&ved=2ahUKEwjypbXa2qT_AhV2l1YBHdzeBVU4FBAWegQIABAC&usg=AOvVaw2SUhzjDh8hpIvpxFuHOVg5",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2023/02/06/070900726/cek-harga-bbm-hari-ini-di-spbu-pertamina-shell-vivo-dan-bp-akr%3Fpage%3Dall&sa=U&ved=2ahUKEwjypbXa2qT_AhV2l1YBHdzeBVU4FBAWegQICBAC&usg=AOvVaw34SOFBZHLsQ-0ZVEJzIb2Z",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/09/05/173000426/mengenal-apa-itu-ron-angka-pada-bahan-bakar-minyak%3Fpage%3Dall&sa=U&ved=2ahUKEwjypbXa2qT_AhV2l1YBHdzeBVU4FBAWegQIAxAC&usg=AOvVaw0LokgMJCWKSvWRDhd4XmQ_",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/08/01/20575151/jokowi-subsidi-bbm-kita-sudah-rp-502-triliun-negara-mana-pun-tak-kuat&sa=U&ved=2ahUKEwjR7dSY3aT_AhUO4WEKHXKIBsM4HhAWegQICRAC&usg=AOvVaw2or4-bH60srVeDKCZcHy9V",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2023/01/04/17482681/bph-migas-penyelundupan-bbm-bersubsidi-capai-14-juta-liter-sepanjang-2022&sa=U&ved=2ahUKEwjR7dSY3aT_AhUO4WEKHXKIBsM4HhAWegQIARAC&usg=AOvVaw229b23r4I3RF5iQz1js2to",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/12/19/113900726/harga-minyak-dunia-turun-pertamina-review-penurunan-harga-bbm-pertamax-dkk%3Fpage%3Dall&sa=U&ved=2ahUKEwjR7dSY3aT_AhUO4WEKHXKIBsM4HhAWegQIBxAC&usg=AOvVaw1JwRZ7puOIKJrSfHfhBwk9",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://jeo.kompas.com/kenaikan-harga-bbm-dari-argumentasi-hingga-dampaknya-bagi-ekonomi&sa=U&ved=2ahUKEwjR7dSY3aT_AhUO4WEKHXKIBsM4HhAWegQIABAC&usg=AOvVaw0MSgQy0jOBtB8SH60or5Ve",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://regional.kompas.com/read/2020/09/07/18365211/desa-di-sumedang-olah-sampah-plastik-jadi-bahan-bakar-minyak%3Fpage%3Dall&sa=U&ved=2ahUKEwjR7dSY3aT_AhUO4WEKHXKIBsM4HhAWegQIAhAC&usg=AOvVaw3TutcPXC0HlaKgf37kAw2j",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/03/13590331/update-harga-bbm-hari-ini-pertalite-rp-10000-liter-solar-rp-6800-pertamax-rp&sa=U&ved=2ahUKEwjR7dSY3aT_AhUO4WEKHXKIBsM4HhAWegQIBBAC&usg=AOvVaw1N92yklS0wziiQWsRo9In3",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/04/06/13090811/jokowi-mustahil-harga-bbm-tidak-naik-situasi-tak-memungkinkan&sa=U&ved=2ahUKEwjR7dSY3aT_AhUO4WEKHXKIBsM4HhAWegQIAxAC&usg=AOvVaw1Rl754r2Xr9rHuJgyyMy6p",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2020/01/13/200000969/perbedaan-pertamax-pertalite-dan-premium%3Fpage%3Dall&sa=U&ved=2ahUKEwjR7dSY3aT_AhUO4WEKHXKIBsM4HhAWegQICBAC&usg=AOvVaw0h91QcxDFtorZuuhyMJXyz",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2023/06/01/132141965/update-harga-bbm-pertamina-shell-dan-bp-akr-per-1-juni-2023%3Fpage%3Dall&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQIAxAC&usg=AOvVaw3FTo14Ecoi6SE6_ISWboik",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2023/01/02/070500465/apa-bahan-bakar-pesawat-&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQICRAC&usg=AOvVaw1J2mnGM5HPaB3IdAxd0b1R",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://megapolitan.kompas.com/read/2022/09/28/13531811/cerita-warga-beralih-ke-vivo-sejak-harga-bbm-naik-lebih-tahan-lama-dan%3Fpage%3Dall&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQIBhAC&usg=AOvVaw02avc9KhTXfDEvpkvq5cva",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2022/08/29/153000965/kapan-harga-bbm-subsidi-naik-ini-jawaban-pertamina%3Fpage%3Dall&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQIBBAC&usg=AOvVaw08tCQjR9ibrT7mN9LJW-ae",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2020/01/31/131120065/pertamina-akan-terapkan-sistem-baru-pengisian-bbm-tidak-bisa-full-tank%3Fpage%3Dall&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQIARAC&usg=AOvVaw1QjxfjLpIbTs5AdVfdMU9A",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/03/19593621/jejak-kenaikan-harga-bbm-di-era-pemerintahan-jokowi&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQIAhAC&usg=AOvVaw2B0N1wHwQgJjrpQKzY2SJ3",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://bola.kompas.com/read/2021/09/30/11520888/saat-mobil-mewah-ronaldo-tidak-kebagian-bahan-bakar-minyak&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQIABAC&usg=AOvVaw3JmNZIPLdonXCmUvyKOnMZ",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2023/01/01/123000065/update-harga-bbm-pertamina-per-1-januari-2023-di-seluruh-indonesia&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQIBxAC&usg=AOvVaw2ZIR49ta-66ySlEQ-p2jDq",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2022/09/08/180500165/mengapa-kenaikan-harga-bbm-bisa-mempengaruhi-berbagai-tarif-dan-harga%3Fpage%3Dall&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQIBRAC&usg=AOvVaw0ndCaxEz7uYi8pqfok4l9L",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/08/08/20543821/menteri-esdm-sebut-harga-bbm-subsidi-belum-akan-naik&sa=U&ved=2ahUKEwicv_n13aT_AhXN3TgGHWOeCn04KBAWegQICBAC&usg=AOvVaw12C40ryzbOD_vPoyXZx43v",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://megapolitan.kompas.com/read/2022/07/18/19012061/kecelakaan-maut-libatkan-truk-pengangkut-bbm-di-transyogi-cibubur-pt%3Fpage%3Dall&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQIAxAC&usg=AOvVaw3wcZguV6HCUjgX8xlHXi5J",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://regional.kompas.com/read/2023/05/03/124906678/penimbunan-bbm-bersubsidi-di-karanganyar-terbongkar-ketahuan-saat-sebuah&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQICRAC&usg=AOvVaw1UkBGbhKvwtTvRJ_92hOSa",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://megapolitan.kompas.com/read/2022/09/13/16262151/demonstrasi-tolak-kenaikan-harga-bbm-di-patung-kuda-diwarnai-aksi-bakar&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQIBhAC&usg=AOvVaw2Y_9WmVj27xDIQw4eJmBWA",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2021/06/15/122132269/keuntungan-dan-kerugian-menggunakan-kendaraan-tenaga-surya%3Fpage%3Dall&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQICBAC&usg=AOvVaw2UxIRNmEC6i3DhYO_jjJSI",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://otomotif.kompas.com/read/2023/03/09/092200615/menghilangkan-kebiasaan-menggoyangkan-mobil-saat-isi-bensin&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQIBxAC&usg=AOvVaw1uu55X0OUQvivy8YZd3xPo",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/08/15/140500226/kuota-bbm-subsidi-menipis-pertamina-bakal-batasi-pembelian-&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQIABAC&usg=AOvVaw33SIZHHi-lcDmpBaeQKiih",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://megapolitan.kompas.com/read/2022/09/19/20530421/buruh-kembali-berunjuk-rasa-tolak-kenaikan-harga-bbm-pada-4-oktober%3Fpage%3Dall&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQIARAC&usg=AOvVaw2Pb7LOn6vQ4-adAlxfg7Yt",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://megapolitan.kompas.com/read/2022/09/02/09523401/gelombang-penolakan-kenaikan-harga-bbm-polisi-imbau-warga-tertib-saat%3Fpage%3Dall&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQIAhAC&usg=AOvVaw2Ii9J60JzMSKh1EJXg3li5",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2023/01/15/203327626/cek-harga-bbm-di-spbu-pertamina-semua-provinsi-per-15-januari-2023%3Fpage%3Dall&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQIBRAC&usg=AOvVaw0qjk-WEoYPMyy9Dzet7bVE",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/07/19/06084221/moeldoko-harga-bbm-mau-dinaikkan-masyarakat-lagi-sulit-kalau-tidak-naik&sa=U&ved=2ahUKEwiWqJXL3qT_AhXiyqACHX-iBl84MhAWegQIBBAC&usg=AOvVaw1oROVtiv_hF1zlwYcRK-dy",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://bandung.kompas.com/read/2022/09/20/150311778/heboh-isu-penurunan-kualitas-pertalite-sejak-harga-bbm-naik-begini-tanggapan&sa=U&ved=2ahUKEwjf7teZ36T_AhUzT2wGHTeoA4k4PBAWegQICRAC&usg=AOvVaw3siaBzVSm6MtLO1o5RTi8L",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2022/06/11/110400765/cara-beli-bbm-subsidi-pakai-aplikasi-mypertamina%3Fpage%3Dall&sa=U&ved=2ahUKEwjf7teZ36T_AhUzT2wGHTeoA4k4PBAWegQIBhAC&usg=AOvVaw1TmnOQYOIbIfbTqlCGwkBl",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2022/08/29/143000665/viral-unggahan-bocoran-harga-bbm-usai-alami-kenaikan-ini-kata-pertamina%3Fpage%3Dall&sa=U&ved=2ahUKEwjf7teZ36T_AhUzT2wGHTeoA4k4PBAWegQIBRAC&usg=AOvVaw13qc5lvQsB5zYXv-6jGPqt",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://otomotif.kompas.com/read/2020/09/29/170100015/mitos-atau-fakta-wajib-matikan-mesin-saat-mengisi-bahan-bakar-minyak-&sa=U&ved=2ahUKEwjf7teZ36T_AhUzT2wGHTeoA4k4PBAWegQIABAC&usg=AOvVaw0dsqd2YGxG21b7S6SaL3gv",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/09/27/211832026/harga-bbm-terbaru-di-spbu-seluruh-indonesia-ada-yang-baru-naik&sa=U&ved=2ahUKEwjf7teZ36T_AhUzT2wGHTeoA4k4PBAWegQIAxAC&usg=AOvVaw1kr_kkVeOYqsDdskoWHHr1",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2022/12/17/153000865/beredar-isu-harga-bbm-pertamina-naik-per-17-desember-ini-kata-pertamina%3Fpage%3Dall&sa=U&ved=2ahUKEwjf7teZ36T_AhUzT2wGHTeoA4k4PBAWegQIBxAC&usg=AOvVaw2yD-eP5wuoHTQChSlTNgRF",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/08/08/20543821/menteri-esdm-sebut-harga-bbm-subsidi-belum-akan-naik&sa=U&ved=2ahUKEwjf7teZ36T_AhUzT2wGHTeoA4k4PBAWegQIARAC&usg=AOvVaw3hCjwY8BH_A6GonOBCJoZw",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://megapolitan.kompas.com/read/2022/09/13/18132181/demo-kenaikan-harga-bbm-di-patung-kuda-kian-ramai-dari-buruh-hingga%3Fpage%3Dall&sa=U&ved=2ahUKEwjf7teZ36T_AhUzT2wGHTeoA4k4PBAWegQIBBAC&usg=AOvVaw3I0b93eJ4eEK7QmYBdZQ35",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/12/10425271/survei-litbang-kompas-mayoritas-publik-nilai-subsidi-bbm-masih-diperlukan&sa=U&ved=2ahUKEwid6Zbu36T_AhVkXmwGHWiYBgE4RhAWegQIBBAC&usg=AOvVaw271cNsBWD30a5g8VmgSuFG",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://bandung.kompas.com/read/2023/03/05/080503978/depo-plumpang-terbakar-pertamina-balongan-jamin-pasokan-bbm-ke-jakarta&sa=U&ved=2ahUKEwid6Zbu36T_AhVkXmwGHWiYBgE4RhAWegQIABAC&usg=AOvVaw0tjaeSNbK1DlOHwPTFfEyK",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/global/read/2021/05/10/140240070/inspirasi-energi-mengapa-minyak-bumi-tidak-dapat-diperbarui%3Fpage%3Dall&sa=U&ved=2ahUKEwid6Zbu36T_AhVkXmwGHWiYBgE4RhAWegQICRAC&usg=AOvVaw3A5XO9igquBgFYqNSxKNXA",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2008/05/07/00211871/bahan.bakar.air.mungkinkah%3Fpage%3Dall&sa=U&ved=2ahUKEwid6Zbu36T_AhVkXmwGHWiYBgE4RhAWegQIBhAC&usg=AOvVaw0eKltaQZrxXc1dGtelk_Fz",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2012/03/19/05525457/infrastruktur.keadilan.dan.bahan%3Fpage%3Dall&sa=U&ved=2ahUKEwid6Zbu36T_AhVkXmwGHWiYBgE4RhAWegQIAxAC&usg=AOvVaw3oC5WIPwRDEDc83sLg-LA5",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/03/30/211214426/perbandingan-harga-bbm-pertamina-ri-vs-petronas-malaysia%3Fpage%3Dall&sa=U&ved=2ahUKEwid6Zbu36T_AhVkXmwGHWiYBgE4RhAWegQIAhAC&usg=AOvVaw2MZeVZ6TGLg9D4xlwtQK2C",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/20/06431731/ketika-jokowi-instruksikan-pemda-ikut-urunan-atasi-dampak-kenaikan-harga-bbm&sa=U&ved=2ahUKEwid6Zbu36T_AhVkXmwGHWiYBgE4RhAWegQIBRAC&usg=AOvVaw3wTLapl3O4VEIugU9C1DLS",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tag/bahan-bakar-minyak-bbm&sa=U&ved=2ahUKEwid6Zbu36T_AhVkXmwGHWiYBgE4RhAWegQICBAB&usg=AOvVaw1WKL6gj_PvAQw1zOqEdPyZ",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/09/01/140734426/shell-juga-turunkan-harga-bbm-per-1-september-simak-rinciannya&sa=U&ved=2ahUKEwjdh-C74KT_AhXCqFYBHSiHCFU4UBAWegQIAhAC&usg=AOvVaw0BquAzC9qq1mBJg6Iuhe-D",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://bandung.kompas.com/read/2023/03/05/080503978/depo-plumpang-terbakar-pertamina-balongan-jamin-pasokan-bbm-ke-jakarta&sa=U&ved=2ahUKEwjdh-C74KT_AhXCqFYBHSiHCFU4UBAWegQICRAC&usg=AOvVaw1rVo1lyxVEYhgr9mqLIX2r",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://regional.kompas.com/read/2022/08/27/114254478/harga-sembako-bisa-ikut-naik-setelah-kenaikan-harga-bbm-pengamat-pemerintah%3Fpage%3Dall&sa=U&ved=2ahUKEwjdh-C74KT_AhXCqFYBHSiHCFU4UBAWegQIBBAC&usg=AOvVaw2QUkbmEld-lQ-bDzeuVws3",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2012/03/19/05525457/infrastruktur.keadilan.dan.bahan%3Fpage%3Dall&sa=U&ved=2ahUKEwjdh-C74KT_AhXCqFYBHSiHCFU4UBAWegQIABAC&usg=AOvVaw2GEIBgcr9Xu5zRkVkF_sbN",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2023/03/01/135137126/daftar-harga-bbm-di-spbu-seluruh-indonesia-berlaku-maret-2023&sa=U&ved=2ahUKEwjdh-C74KT_AhXCqFYBHSiHCFU4UBAWegQIAxAC&usg=AOvVaw0K1-TGQLCtF5x3DlnZtH62",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/10/05/083000526/harga-pertamax-turun-cek-perbandingan-harga-bbm-di-spbu-pertamina-vivo-shell&sa=U&ved=2ahUKEwjdh-C74KT_AhXCqFYBHSiHCFU4UBAWegQIBhAC&usg=AOvVaw1-RhQwK6aqxU2dNgEn7OjT",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://megapolitan.kompas.com/read/2022/09/19/20530421/buruh-kembali-berunjuk-rasa-tolak-kenaikan-harga-bbm-pada-4-oktober%3Fpage%3Dall&sa=U&ved=2ahUKEwjdh-C74KT_AhXCqFYBHSiHCFU4UBAWegQIARAC&usg=AOvVaw2miqFBg_frJ5liWeaXyUc5",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2022/09/03/171500126/mengapa-harga-bbm-naik-saat-tren-harga-minyak-dunia-turun-ini-penjelasan-sri&sa=U&ved=2ahUKEwjdh-C74KT_AhXCqFYBHSiHCFU4UBAWegQIBxAC&usg=AOvVaw0bGnqvSagdjbSs2Hcw4dmF",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/09/06/21045701/demo-tolak-kenaikan-harga-bbm-terjadi-di-banyak-daerah-puan-dpr-dengar&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQIAhAC&usg=AOvVaw3hsefPmlZJ9wVsyAZpuFM8",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/xml/2014/11/17/21235521/Ini.Kompensasi.Kenaikan.Harga.BBM.Menurut.Jokowi&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQICBAC&usg=AOvVaw1SvIHHrxZyLc9ZrVOnMqfH",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://kilaskementerian.kompas.com/ditjen-ebtke/read/2022/12/16/12322091/kurangi-impor-solar-pemerintah-tetapkan-alokasi-biodiesel-tahun-2023-sebesar&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQICRAC&usg=AOvVaw3TV-7WepDve34CboUxs3CY",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://regional.kompas.com/read/2023/03/02/140456178/polisi-bongkar-transaksi-jual-beli-bbm-subsidi-ilegal-di-sragen-pemilik&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQIARAC&usg=AOvVaw34a52NS7ttLk5wWYNGI9kv",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/skola/read/2022/10/27/130000969/mengenal-kilang-minyak-di-indonesia%3Fpage%3Dall&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQIAxAC&usg=AOvVaw0zV1qMof4h0nMMoDsW2-BF",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://nasional.kompas.com/read/2022/07/20/10170021/saat-pemerintah-kembali-singgung-besarnya-subsidi-bbm-isyarat-harga-segera&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQIABAC&usg=AOvVaw2QdrPlbCypX_HGBaYb7z2g",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://money.kompas.com/read/2023/04/01/114022626/daftar-harga-bbm-di-spbu-seluruh-indonesia-berlaku-april-2023%3Fpage%3Dall&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQIBhAC&usg=AOvVaw3W68iLfnCSukiaTUv6I--U",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://www.kompas.com/tren/read/2022/09/02/073500465/update-harga-bbm-hari-ini-seluruh-indonesia-pertalite-hingga-pertamax&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQIBBAC&usg=AOvVaw0TgfvJ0L01DTL05p--7UCF",
        "https://www.google.com/url?client=internal-element-cse&cx=partner-pub-9012468469771973:uc7pie-r3ad&q=https://otomotif.kompas.com/read/2023/01/16/121200715/ini-efek-jika-sering-gonta-ganti-jenis-bbm&sa=U&ved=2ahUKEwigg43-4KT_AhX29zgGHfEKCTU4WhAWegQIBxAC&usg=AOvVaw2Wvl5-6xABooCsffIY77Xx",


              ]

import nltk
nltk.download('punkt')
text = []
summarize = []
for url in list_of_urls:
  url_i = newspaper.Article(url="%s" % (url), language='id')
  url_i.download()
  url_i.parse()
  url_i.nlp()
  print('Judul:', url_i.title)
  print('Penulis:', url_i.authors)
  print('Sumber:', url_i.source_url)
  print('Rangkuman :', url_i.summary)
  summarize.append(url_i.summary)
  text.append(url_i.text)

teks_kominfo = ' '.join(map(str, text))

print(teks_kominfo)

import pandas as pd
d = {'teks': [teks_kominfo]}
data_kominfo = pd.DataFrame(data=d)

df_kominfo = pd.DataFrame()
for url in list_of_urls:
  url_i = newspaper.Article(url="%s" % (url), language='id')
  url_i.download()
  url_i.parse()
  url_i.nlp()

  df = pd.DataFrame(columns = ['Judul', 'Penulis', 'Teks', 'Rangkuman', 'Sumber'])

  df['Penulis'] = url_i.authors
  df['Judul'] = url_i.title
  df['Teks'] = url_i.text
  df['Rangkuman'] = url_i.summary
  df['Sumber'] = url_i.source_url

  df_kominfo = df_kominfo.append(df, ignore_index = True)

df_kominfo.head(1000)

df_kominfo.to_csv('data berita kompas.csv', index=True)

data = pd.read_csv('data berita kompas.csv')
data.head()